package skeleton

import "time"

// Skeleton is the entity this package owns.
//
// It carries no persistence method and holds no database handle: reading and
// writing belong to the repository, so nothing loads by being looked at and no
// call site can reach a row through a value it already has.
type Skeleton struct {
	// ID is the identifier. It is generated by the application rather than by
	// the database, because a DEFAULT that produces a uuid is spelled
	// differently in every engine.
	ID string

	// TenantID is the customer the row belongs to. It is written from the
	// Grant and read back so the policy can compare it against the subject's
	// tenant.
	TenantID string

	// Name is what a person calls this record.
	Name string

	// CreatedAt is when the row was written, in UTC.
	CreatedAt time.Time
}

// Resource is the list of fields one Skeleton is allowed to answer with.
//
// A declared list rather than the entity itself. An encoder handed the entity
// answers with whatever fields it happens to have, including the ones somebody
// adds later without ever opening the handler -- and TenantID is exactly such a
// field: it names another customer's identifier and belongs in no response.
type Resource struct{ record Skeleton }

// NewResource wraps one record for the response.
func NewResource(record Skeleton) Resource { return Resource{record: record} }

// ToArray returns the fields that may leave, by name.
func (r Resource) ToArray() map[string]any {
	return map[string]any{
		"id":         r.record.ID,
		"name":       r.record.Name,
		"created_at": r.record.CreatedAt.UTC().Format(time.RFC3339),
	}
}

// With returns what goes beside the fields at the top level of the response.
// Nothing does here, and a resource that has nothing to add says so by
// answering nil.
func (r Resource) With() map[string]any { return nil }

// Collection is a page of records as one response.
type Collection struct {
	records []Skeleton
	// cursor is what the next page asks for, empty when this page is the last
	// one. It goes beside the items rather than inside them: it describes the
	// answer, not the things answered with.
	cursor string
}

// NewCollection wraps a page of records for the response. The cursor is what
// the next request passes back, and is empty when there is no next page.
func NewCollection(records []Skeleton, cursor string) Collection {
	return Collection{records: records, cursor: cursor}
}

// ToArray returns the page under a single key, so that the shape of the
// response does not change when a second key is added beside it.
func (c Collection) ToArray() map[string]any {
	items := make([]map[string]any, 0, len(c.records))
	for _, record := range c.records {
		items = append(items, NewResource(record).ToArray())
	}
	return map[string]any{"items": items}
}

// With returns the cursor of the next page, and nothing when there is none.
func (c Collection) With() map[string]any {
	if c.cursor == "" {
		return nil
	}
	return map[string]any{"next_cursor": c.cursor}
}
