package apidocs

var operationDefinitions = map[string]operationDefinition{
	"whatsapp.messages.text": {
		summary:             "Send a text message",
		description:         "Sends synchronously unless options.mentionAll is true.",
		tag:                 "Messages",
		parameterComponents: []string{"WhatsAppInstanceName"},
		body:                &bodyDefinition{contentType: "application/json", schemaComponent: "WhatsAppSendTextRequest", required: true},
		responses: []operationResponseDefinition{
			{status: 200, component: "WhatsAppMessageSent"},
			{status: 202, component: "WhatsAppAccepted"},
			{status: 400, component: "WhatsAppBadRequest"},
			{status: 403, component: "WhatsAppForbidden"},
			{status: 404, component: "WhatsAppNotFound"},
			{status: 406, component: "WhatsAppNotAcceptable"},
			{status: 409, component: "WhatsAppConflict"},
			{status: 413, component: "WhatsAppPayloadTooLarge"},
			{status: 500, component: "WhatsAppInternalServerError"},
			{status: 503, component: "WhatsAppServiceUnavailable"},
		},
	},
	"whatsapp.messages.link": {
		summary:             "Send a link message",
		description:         "Supports options.mentionAll.",
		tag:                 "Messages",
		parameterComponents: []string{"WhatsAppInstanceName"},
		body:                &bodyDefinition{contentType: "application/json", schemaComponent: "WhatsAppSendLinkRequest", required: true},
		responses: []operationResponseDefinition{
			{status: 200, component: "WhatsAppMessageSent"},
			{status: 202, component: "WhatsAppAccepted"},
			{status: 400, component: "WhatsAppBadRequest"},
			{status: 403, component: "WhatsAppForbidden"},
			{status: 404, component: "WhatsAppNotFound"},
			{status: 406, component: "WhatsAppNotAcceptable"},
			{status: 409, component: "WhatsAppConflict"},
			{status: 413, component: "WhatsAppPayloadTooLarge"},
			{status: 500, component: "WhatsAppInternalServerError"},
			{status: 503, component: "WhatsAppServiceUnavailable"},
		},
	},
	"whatsapp.messages.media": {
		summary:             "Send media from URL",
		description:         "Supports image, document, video, audio and ptv. Supports options.mentionAll.",
		tag:                 "Messages",
		parameterComponents: []string{"WhatsAppInstanceName"},
		body:                &bodyDefinition{contentType: "application/json", schemaComponent: "WhatsAppSendMediaRequest", required: true},
		responses: []operationResponseDefinition{
			{status: 200, component: "WhatsAppMessageSent"},
			{status: 202, component: "WhatsAppAccepted"},
			{status: 400, component: "WhatsAppBadRequest"},
			{status: 403, component: "WhatsAppForbidden"},
			{status: 404, component: "WhatsAppNotFound"},
			{status: 406, component: "WhatsAppNotAcceptable"},
			{status: 409, component: "WhatsAppConflict"},
			{status: 413, component: "WhatsAppPayloadTooLarge"},
			{status: 500, component: "WhatsAppInternalServerError"},
			{status: 503, component: "WhatsAppServiceUnavailable"},
		},
	},
	"whatsapp.messages.media.file": {
		summary:             "Send media from multipart file upload",
		description:         "Uses multipart field attachment. Supports options.mentionAll through multipart form fields.",
		tag:                 "Messages",
		parameterComponents: []string{"WhatsAppInstanceName"},
		body:                &bodyDefinition{contentType: "multipart/form-data", schemaComponent: "WhatsAppSendMediaFileRequest", required: true},
		responses: []operationResponseDefinition{
			{status: 200, component: "WhatsAppMessageSent"},
			{status: 202, component: "WhatsAppAccepted"},
			{status: 400, component: "WhatsAppBadRequest"},
			{status: 403, component: "WhatsAppForbidden"},
			{status: 404, component: "WhatsAppNotFound"},
			{status: 406, component: "WhatsAppNotAcceptable"},
			{status: 409, component: "WhatsAppConflict"},
			{status: 413, component: "WhatsAppPayloadTooLarge"},
			{status: 500, component: "WhatsAppInternalServerError"},
			{status: 503, component: "WhatsAppServiceUnavailable"},
		},
	},
	"whatsapp.messages.audio": {
		summary:             "Send WhatsApp PTT audio from URL",
		description:         "Downloads and prepares audio as WhatsApp PTT. Supports options.mentionAll.",
		tag:                 "Messages",
		parameterComponents: []string{"WhatsAppInstanceName"},
		body:                &bodyDefinition{contentType: "application/json", schemaComponent: "WhatsAppSendWhatsAppAudioRequest", required: true},
		responses: []operationResponseDefinition{
			{status: 200, component: "WhatsAppMessageSent"},
			{status: 202, component: "WhatsAppAccepted"},
			{status: 400, component: "WhatsAppBadRequest"},
			{status: 403, component: "WhatsAppForbidden"},
			{status: 404, component: "WhatsAppNotFound"},
			{status: 406, component: "WhatsAppNotAcceptable"},
			{status: 409, component: "WhatsAppConflict"},
			{status: 413, component: "WhatsAppPayloadTooLarge"},
			{status: 415, component: "WhatsAppUnsupportedMediaType"},
			{status: 500, component: "WhatsAppInternalServerError"},
			{status: 503, component: "WhatsAppServiceUnavailable"},
		},
	},
	"whatsapp.messages.audio.file": {
		summary:             "Send WhatsApp PTT audio from multipart file upload",
		description:         "Uses multipart field attachment. Supports options.mentionAll through multipart form fields.",
		tag:                 "Messages",
		parameterComponents: []string{"WhatsAppInstanceName"},
		body:                &bodyDefinition{contentType: "multipart/form-data", schemaComponent: "WhatsAppSendWhatsAppAudioFileRequest", required: true},
		responses: []operationResponseDefinition{
			{status: 200, component: "WhatsAppMessageSent"},
			{status: 202, component: "WhatsAppAccepted"},
			{status: 400, component: "WhatsAppBadRequest"},
			{status: 403, component: "WhatsAppForbidden"},
			{status: 404, component: "WhatsAppNotFound"},
			{status: 406, component: "WhatsAppNotAcceptable"},
			{status: 409, component: "WhatsAppConflict"},
			{status: 413, component: "WhatsAppPayloadTooLarge"},
			{status: 415, component: "WhatsAppUnsupportedMediaType"},
			{status: 500, component: "WhatsAppInternalServerError"},
			{status: 503, component: "WhatsAppServiceUnavailable"},
		},
	},
	"whatsapp.messages.contact": {
		summary:             "Send one or more contact cards",
		description:         "Supports quoted message, delay, presence, external attributes and options.mentionAll.",
		tag:                 "Messages",
		parameterComponents: []string{"WhatsAppInstanceName"},
		body:                &bodyDefinition{contentType: "application/json", schemaComponent: "WhatsAppSendContactRequest", required: true},
		responses: []operationResponseDefinition{
			{status: 200, component: "WhatsAppMessageSent"},
			{status: 202, component: "WhatsAppAccepted"},
			{status: 400, component: "WhatsAppBadRequest"},
			{status: 403, component: "WhatsAppForbidden"},
			{status: 404, component: "WhatsAppNotFound"},
			{status: 406, component: "WhatsAppNotAcceptable"},
			{status: 409, component: "WhatsAppConflict"},
			{status: 413, component: "WhatsAppPayloadTooLarge"},
			{status: 500, component: "WhatsAppInternalServerError"},
			{status: 503, component: "WhatsAppServiceUnavailable"},
		},
	},
	"whatsapp.messages.location": {
		summary:             "Send a location",
		description:         "Supports quoted message, delay, presence, external attributes and options.mentionAll.",
		tag:                 "Messages",
		parameterComponents: []string{"WhatsAppInstanceName"},
		body:                &bodyDefinition{contentType: "application/json", schemaComponent: "WhatsAppSendLocationRequest", required: true},
		responses: []operationResponseDefinition{
			{status: 200, component: "WhatsAppMessageSent"},
			{status: 202, component: "WhatsAppAccepted"},
			{status: 400, component: "WhatsAppBadRequest"},
			{status: 403, component: "WhatsAppForbidden"},
			{status: 404, component: "WhatsAppNotFound"},
			{status: 406, component: "WhatsAppNotAcceptable"},
			{status: 409, component: "WhatsAppConflict"},
			{status: 413, component: "WhatsAppPayloadTooLarge"},
			{status: 500, component: "WhatsAppInternalServerError"},
			{status: 503, component: "WhatsAppServiceUnavailable"},
		},
	},
	"whatsapp.messages.reaction": {
		summary:             "Send a reaction to an existing message",
		description:         "Does not support options.mentionAll because ReactionMessage has no ContextInfo.MentionedJID.",
		tag:                 "Messages",
		parameterComponents: []string{"WhatsAppInstanceName"},
		body:                &bodyDefinition{contentType: "application/json", schemaComponent: "WhatsAppSendReactionRequest", required: true},
		responses: []operationResponseDefinition{
			{status: 200, component: "WhatsAppMessageSent"},
			{status: 400, component: "WhatsAppBadRequest"},
			{status: 403, component: "WhatsAppForbidden"},
			{status: 404, component: "WhatsAppNotFound"},
			{status: 406, component: "WhatsAppNotAcceptable"},
			{status: 413, component: "WhatsAppPayloadTooLarge"},
			{status: 500, component: "WhatsAppInternalServerError"},
			{status: 503, component: "WhatsAppServiceUnavailable"},
		},
	},
	"whatsapp.instances.store": {
		summary: "Create a WhatsApp instance",
		tag:     "Instances",
		body:    &bodyDefinition{contentType: "application/json", schemaComponent: "WhatsAppCreateInstanceRequest", required: true},
		responses: []operationResponseDefinition{
			{status: 201, component: "WhatsAppInstanceCreated"},
			{status: 400, component: "WhatsAppBadRequest"},
			{status: 403, component: "WhatsAppForbidden"},
			{status: 404, component: "WhatsAppNotFound"},
			{status: 409, component: "WhatsAppConflict"},
			{status: 413, component: "WhatsAppPayloadTooLarge"},
			{status: 500, component: "WhatsAppInternalServerError"},
		},
	},
	"whatsapp.instances.index": {
		summary: "List instances in the configured tenant",
		tag:     "Instances",
		queries: []queryDefinition{
			{name: "instanceName", description: "", schema: queryInstanceName},
			{name: "limit", description: "", schema: queryLimit},
			{name: "cursor", description: "Opaque cursor returned as nextCursor by the previous page.", schema: queryString},
		},
		responses: []operationResponseDefinition{
			{status: 200, component: "WhatsAppInstanceList"},
			{status: 400, component: "WhatsAppBadRequest"},
			{status: 403, component: "WhatsAppForbidden"},
			{status: 500, component: "WhatsAppInternalServerError"},
		},
	},
	"whatsapp.instances.show": {
		summary:             "Find an instance by name",
		tag:                 "Instances",
		parameterComponents: []string{"WhatsAppInstanceName"},
		responses: []operationResponseDefinition{
			{status: 200, component: "WhatsAppInstanceFound"},
			{status: 400, component: "WhatsAppBadRequest"},
			{status: 403, component: "WhatsAppForbidden"},
			{status: 404, component: "WhatsAppNotFound"},
			{status: 500, component: "WhatsAppInternalServerError"},
		},
	},
	"whatsapp.instances.destroy": {
		summary:             "Delete an instance",
		tag:                 "Instances",
		parameterComponents: []string{"WhatsAppInstanceName"},
		queries: []queryDefinition{
			{name: "force", description: "", schema: queryBoolean},
		},
		responses: []operationResponseDefinition{
			{status: 200, component: "WhatsAppInstanceDeleted"},
			{status: 400, component: "WhatsAppBadRequest"},
			{status: 403, component: "WhatsAppForbidden"},
			{status: 404, component: "WhatsAppNotFound"},
			{status: 409, component: "WhatsAppConflict"},
			{status: 500, component: "WhatsAppInternalServerError"},
			{status: 503, component: "WhatsAppServiceUnavailable"},
		},
	},
	"whatsapp.connection.qr": {
		summary:             "Start QR pairing",
		tag:                 "Connection",
		parameterComponents: []string{"WhatsAppInstanceName"},
		responses: []operationResponseDefinition{
			{status: 200, component: "WhatsAppQRCodeConnection"},
			{status: 400, component: "WhatsAppBadRequest"},
			{status: 403, component: "WhatsAppForbidden"},
			{status: 404, component: "WhatsAppNotFound"},
			{status: 408, component: "WhatsAppRequestTimeout"},
			{status: 409, component: "WhatsAppConflict"},
			{status: 422, component: "WhatsAppUnprocessableEntity"},
			{status: 500, component: "WhatsAppInternalServerError"},
			{status: 503, component: "WhatsAppServiceUnavailable"},
		},
	},
	"whatsapp.connection.phone": {
		summary:             "Start phone-code pairing",
		tag:                 "Connection",
		parameterComponents: []string{"WhatsAppInstanceName"},
		body:                &bodyDefinition{contentType: "application/json", schemaComponent: "WhatsAppPhonePairingRequest", required: true},
		responses: []operationResponseDefinition{
			{status: 200, component: "WhatsAppPhonePairing"},
			{status: 400, component: "WhatsAppBadRequest"},
			{status: 403, component: "WhatsAppForbidden"},
			{status: 404, component: "WhatsAppNotFound"},
			{status: 409, component: "WhatsAppConflict"},
			{status: 500, component: "WhatsAppInternalServerError"},
			{status: 503, component: "WhatsAppServiceUnavailable"},
		},
	},
	"whatsapp.connection.passkey.challenge": {
		summary:             "Obtain the active WebAuthn challenge",
		tag:                 "Connection",
		parameterComponents: []string{"WhatsAppInstanceName"},
		responses: []operationResponseDefinition{
			{status: 200, component: "WhatsAppPasskeyChallenge"},
			{status: 400, component: "WhatsAppBadRequest"},
			{status: 403, component: "WhatsAppForbidden"},
			{status: 404, component: "WhatsAppNotFound"},
			{status: 409, component: "WhatsAppConflict"},
			{status: 422, component: "WhatsAppUnprocessableEntity"},
			{status: 500, component: "WhatsAppInternalServerError"},
			{status: 503, component: "WhatsAppServiceUnavailable"},
		},
	},
	"whatsapp.connection.passkey.assertion": {
		summary:             "Submit a WebAuthn assertion",
		tag:                 "Connection",
		parameterComponents: []string{"WhatsAppInstanceName"},
		body:                &bodyDefinition{contentType: "application/json", schemaComponent: "WhatsAppPasskeyAssertionRequest", required: true},
		responses: []operationResponseDefinition{
			{status: 202, component: "WhatsAppPasskeyAssertionAccepted"},
			{status: 400, component: "WhatsAppBadRequest"},
			{status: 403, component: "WhatsAppForbidden"},
			{status: 404, component: "WhatsAppNotFound"},
			{status: 409, component: "WhatsAppConflict"},
			{status: 410, component: "WhatsAppGone"},
			{status: 413, component: "WhatsAppPayloadTooLarge"},
			{status: 422, component: "WhatsAppUnprocessableEntity"},
			{status: 500, component: "WhatsAppInternalServerError"},
			{status: 503, component: "WhatsAppServiceUnavailable"},
		},
	},
	"whatsapp.connection.show": {
		summary:             "Get connection state",
		tag:                 "Connection",
		parameterComponents: []string{"WhatsAppInstanceName"},
		responses: []operationResponseDefinition{
			{status: 200, component: "WhatsAppConnectionState"},
			{status: 400, component: "WhatsAppBadRequest"},
			{status: 403, component: "WhatsAppForbidden"},
			{status: 404, component: "WhatsAppNotFound"},
			{status: 500, component: "WhatsAppInternalServerError"},
		},
	},
	"whatsapp.connection.destroy": {
		summary:             "Log out and remove the active WhatsApp session",
		tag:                 "Connection",
		parameterComponents: []string{"WhatsAppInstanceName"},
		responses: []operationResponseDefinition{
			{status: 200, component: "WhatsAppLogout"},
			{status: 400, component: "WhatsAppBadRequest"},
			{status: 403, component: "WhatsAppForbidden"},
			{status: 404, component: "WhatsAppNotFound"},
			{status: 409, component: "WhatsAppConflict"},
			{status: 500, component: "WhatsAppInternalServerError"},
			{status: 503, component: "WhatsAppServiceUnavailable"},
		},
	},
	"whatsapp.webhook.update": {
		summary:             "Create or update the instance webhook",
		tag:                 "Webhooks",
		parameterComponents: []string{"WhatsAppInstanceName"},
		body:                &bodyDefinition{contentType: "application/json", schemaComponent: "WhatsAppSetWebhookRequest", required: true},
		responses: []operationResponseDefinition{
			{status: 200, component: "WhatsAppWebhook"},
			{status: 400, component: "WhatsAppBadRequest"},
			{status: 403, component: "WhatsAppForbidden"},
			{status: 404, component: "WhatsAppNotFound"},
			{status: 409, component: "WhatsAppConflict"},
			{status: 413, component: "WhatsAppPayloadTooLarge"},
			{status: 500, component: "WhatsAppInternalServerError"},
		},
	},
	"whatsapp.webhook.show": {
		summary:             "Get the instance webhook",
		tag:                 "Webhooks",
		parameterComponents: []string{"WhatsAppInstanceName"},
		responses: []operationResponseDefinition{
			{status: 200, component: "WhatsAppWebhook"},
			{status: 400, component: "WhatsAppBadRequest"},
			{status: 403, component: "WhatsAppForbidden"},
			{status: 404, component: "WhatsAppNotFound"},
			{status: 500, component: "WhatsAppInternalServerError"},
		},
	},
	"whatsapp.messages.index": {
		summary:             "Search persisted messages",
		tag:                 "Messages",
		parameterComponents: []string{"WhatsAppInstanceName"},
		body:                &bodyDefinition{contentType: "application/json", schemaComponent: "WhatsAppMessageSearchRequest", required: false},
		responses: []operationResponseDefinition{
			{status: 200, component: "WhatsAppMessageList"},
			{status: 400, component: "WhatsAppBadRequest"},
			{status: 403, component: "WhatsAppForbidden"},
			{status: 404, component: "WhatsAppNotFound"},
			{status: 413, component: "WhatsAppPayloadTooLarge"},
			{status: 422, component: "WhatsAppUnprocessableEntity"},
			{status: 500, component: "WhatsAppInternalServerError"},
		},
	},
	"whatsapp.messages.read": {
		summary:             "Mark persisted WhatsApp messages as read",
		tag:                 "Messages",
		parameterComponents: []string{"WhatsAppInstanceName"},
		body:                &bodyDefinition{contentType: "application/json", schemaComponent: "WhatsAppReadMessagesRequest", required: true},
		responses: []operationResponseDefinition{
			{status: 200, component: "WhatsAppMessagesRead"},
			{status: 400, component: "WhatsAppBadRequest"},
			{status: 403, component: "WhatsAppForbidden"},
			{status: 404, component: "WhatsAppNotFound"},
			{status: 406, component: "WhatsAppNotAcceptable"},
			{status: 413, component: "WhatsAppPayloadTooLarge"},
			{status: 422, component: "WhatsAppUnprocessableEntity"},
			{status: 500, component: "WhatsAppInternalServerError"},
			{status: 503, component: "WhatsAppServiceUnavailable"},
		},
	},
	"whatsapp.messages.destroy": {
		summary:             "Delete a message by positive local numeric ID",
		tag:                 "Messages",
		parameterComponents: []string{"WhatsAppInstanceName", "WhatsAppMessage"},
		responses: []operationResponseDefinition{
			{status: 204, description: "Message deleted."},
			{status: 400, component: "WhatsAppBadRequest"},
			{status: 403, component: "WhatsAppForbidden"},
			{status: 404, component: "WhatsAppNotFound"},
			{status: 406, component: "WhatsAppNotAcceptable"},
			{status: 422, component: "WhatsAppUnprocessableEntity"},
			{status: 500, component: "WhatsAppInternalServerError"},
			{status: 503, component: "WhatsAppServiceUnavailable"},
		},
	},
	"whatsapp.messages.update": {
		summary:             "Edit an outgoing message by local ID or WhatsApp key ID",
		tag:                 "Messages",
		parameterComponents: []string{"WhatsAppInstanceName", "WhatsAppMessage"},
		body:                &bodyDefinition{contentType: "application/json", schemaComponent: "WhatsAppEditMessageRequest", required: true},
		responses: []operationResponseDefinition{
			{status: 200, component: "WhatsAppMessageFound"},
			{status: 400, component: "WhatsAppBadRequest"},
			{status: 403, component: "WhatsAppForbidden"},
			{status: 404, component: "WhatsAppNotFound"},
			{status: 406, component: "WhatsAppNotAcceptable"},
			{status: 413, component: "WhatsAppPayloadTooLarge"},
			{status: 422, component: "WhatsAppUnprocessableEntity"},
			{status: 500, component: "WhatsAppInternalServerError"},
			{status: 503, component: "WhatsAppServiceUnavailable"},
		},
	},
	"whatsapp.messages.media.download": {
		summary:             "Download message media",
		tag:                 "Messages",
		parameterComponents: []string{"WhatsAppInstanceName"},
		queries: []queryDefinition{
			{name: "binary", description: "", schema: queryBoolean},
		},
		body: &bodyDefinition{contentType: "application/json", schemaComponent: "WhatsAppMediaDownloadRequest", required: true},
		responses: []operationResponseDefinition{
			{status: 200, description: "Raw media when binary=true; otherwise multipart metadata and file.", media: []mediaDefinition{
				{contentType: "application/octet-stream", schemaComponent: "WhatsAppDownloadBinary"},
				{contentType: "multipart/form-data", schemaComponent: "WhatsAppDownloadMultipart"},
			}},
			{status: 400, component: "WhatsAppBadRequest"},
			{status: 403, component: "WhatsAppForbidden"},
			{status: 404, component: "WhatsAppNotFound"},
			{status: 406, component: "WhatsAppNotAcceptable"},
			{status: 413, component: "WhatsAppPayloadTooLarge"},
			{status: 422, component: "WhatsAppUnprocessableEntity"},
			{status: 500, component: "WhatsAppInternalServerError"},
			{status: 503, component: "WhatsAppServiceUnavailable"},
		},
	},
	"whatsapp.contacts.check": {
		summary:             "Check WhatsApp registration for up to 100 numbers",
		tag:                 "Contacts",
		parameterComponents: []string{"WhatsAppInstanceName"},
		body:                &bodyDefinition{contentType: "application/json", schemaComponent: "WhatsAppContactsCheckRequest", required: true},
		responses: []operationResponseDefinition{
			{status: 200, component: "WhatsAppContactsChecked"},
			{status: 400, component: "WhatsAppBadRequest"},
			{status: 403, component: "WhatsAppForbidden"},
			{status: 404, component: "WhatsAppNotFound"},
			{status: 413, component: "WhatsAppPayloadTooLarge"},
			{status: 422, component: "WhatsAppUnprocessableEntity"},
			{status: 500, component: "WhatsAppInternalServerError"},
			{status: 503, component: "WhatsAppServiceUnavailable"},
		},
	},
	"whatsapp.contacts.profile-picture": {
		summary:             "Fetch a profile picture URL",
		tag:                 "Contacts",
		parameterComponents: []string{"WhatsAppInstanceName"},
		body:                &bodyDefinition{contentType: "application/json", schemaComponent: "WhatsAppProfilePictureRequest", required: true},
		responses: []operationResponseDefinition{
			{status: 200, component: "WhatsAppProfilePicture"},
			{status: 400, component: "WhatsAppBadRequest"},
			{status: 403, component: "WhatsAppForbidden"},
			{status: 404, component: "WhatsAppNotFound"},
			{status: 409, component: "WhatsAppConflict"},
			{status: 413, component: "WhatsAppPayloadTooLarge"},
			{status: 422, component: "WhatsAppUnprocessableEntity"},
			{status: 500, component: "WhatsAppInternalServerError"},
			{status: 503, component: "WhatsAppServiceUnavailable"},
		},
	},
	"whatsapp.chats.archive": {
		summary:             "Archive or unarchive a chat",
		tag:                 "Chats",
		parameterComponents: []string{"WhatsAppInstanceName"},
		body:                &bodyDefinition{contentType: "application/json", schemaComponent: "WhatsAppArchiveChatRequest", required: true},
		responses: []operationResponseDefinition{
			{status: 204, description: "Chat state updated."},
			{status: 400, component: "WhatsAppBadRequest"},
			{status: 403, component: "WhatsAppForbidden"},
			{status: 404, component: "WhatsAppNotFound"},
			{status: 413, component: "WhatsAppPayloadTooLarge"},
			{status: 422, component: "WhatsAppUnprocessableEntity"},
			{status: 500, component: "WhatsAppInternalServerError"},
			{status: 503, component: "WhatsAppServiceUnavailable"},
		},
	},
	"whatsapp.calls.reject": {
		summary:             "Reject an incoming call",
		tag:                 "Calls",
		parameterComponents: []string{"WhatsAppInstanceName"},
		body:                &bodyDefinition{contentType: "application/json", schemaComponent: "WhatsAppRejectCallRequest", required: true},
		responses: []operationResponseDefinition{
			{status: 204, description: "Call rejected."},
			{status: 400, component: "WhatsAppBadRequest"},
			{status: 403, component: "WhatsAppForbidden"},
			{status: 404, component: "WhatsAppNotFound"},
			{status: 413, component: "WhatsAppPayloadTooLarge"},
			{status: 422, component: "WhatsAppUnprocessableEntity"},
			{status: 500, component: "WhatsAppInternalServerError"},
			{status: 503, component: "WhatsAppServiceUnavailable"},
		},
	},
	"whatsapp.groups.store": {
		summary:             "Create a WhatsApp group",
		tag:                 "Groups",
		parameterComponents: []string{"WhatsAppInstanceName"},
		body:                &bodyDefinition{contentType: "application/json", schemaComponent: "WhatsAppCreateGroupRequest", required: true},
		responses: []operationResponseDefinition{
			{status: 201, component: "WhatsAppGroupInfo"},
			{status: 400, component: "WhatsAppBadRequest"},
			{status: 403, component: "WhatsAppForbidden"},
			{status: 404, component: "WhatsAppNotFound"},
			{status: 413, component: "WhatsAppPayloadTooLarge"},
			{status: 500, component: "WhatsAppInternalServerError"},
			{status: 503, component: "WhatsAppServiceUnavailable"},
		},
	},
	"whatsapp.groups.picture.update": {
		summary:             "Update a group picture",
		tag:                 "Groups",
		parameterComponents: []string{"WhatsAppInstanceName", "WhatsAppGroup"},
		body:                &bodyDefinition{contentType: "application/json", schemaComponent: "WhatsAppUpdateGroupPictureRequest", required: true},
		responses: []operationResponseDefinition{
			{status: 200, component: "WhatsAppGroupInfo"},
			{status: 400, component: "WhatsAppBadRequest"},
			{status: 403, component: "WhatsAppForbidden"},
			{status: 404, component: "WhatsAppNotFound"},
			{status: 413, component: "WhatsAppPayloadTooLarge"},
			{status: 500, component: "WhatsAppInternalServerError"},
			{status: 503, component: "WhatsAppServiceUnavailable"},
		},
	},
	"whatsapp.groups.invite.show": {
		summary:             "Get the current group invite code",
		tag:                 "Groups",
		parameterComponents: []string{"WhatsAppInstanceName", "WhatsAppGroup"},
		responses: []operationResponseDefinition{
			{status: 200, component: "WhatsAppGroupInvite"},
			{status: 400, component: "WhatsAppBadRequest"},
			{status: 403, component: "WhatsAppForbidden"},
			{status: 404, component: "WhatsAppNotFound"},
			{status: 500, component: "WhatsAppInternalServerError"},
			{status: 503, component: "WhatsAppServiceUnavailable"},
		},
	},
	"whatsapp.groups.invite.destroy": {
		summary:             "Revoke the current group invite code",
		tag:                 "Groups",
		parameterComponents: []string{"WhatsAppInstanceName", "WhatsAppGroup"},
		responses: []operationResponseDefinition{
			{status: 200, description: "Invite revoked; empty body."},
			{status: 400, component: "WhatsAppBadRequest"},
			{status: 403, component: "WhatsAppForbidden"},
			{status: 404, component: "WhatsAppNotFound"},
			{status: 500, component: "WhatsAppInternalServerError"},
			{status: 503, component: "WhatsAppServiceUnavailable"},
		},
	},
	"whatsapp.groups.participants.update": {
		summary:             "Add, remove, promote or demote group participants",
		tag:                 "Groups",
		parameterComponents: []string{"WhatsAppInstanceName", "WhatsAppGroup"},
		body:                &bodyDefinition{contentType: "application/json", schemaComponent: "WhatsAppUpdateParticipantsRequest", required: true},
		responses: []operationResponseDefinition{
			{status: 200, description: "Participants updated; empty body."},
			{status: 400, component: "WhatsAppBadRequest"},
			{status: 403, component: "WhatsAppForbidden"},
			{status: 404, component: "WhatsAppNotFound"},
			{status: 413, component: "WhatsAppPayloadTooLarge"},
			{status: 500, component: "WhatsAppInternalServerError"},
			{status: 503, component: "WhatsAppServiceUnavailable"},
		},
	},
	"whatsapp.groups.leave": {
		summary:             "Leave a group",
		tag:                 "Groups",
		parameterComponents: []string{"WhatsAppInstanceName", "WhatsAppGroup"},
		responses: []operationResponseDefinition{
			{status: 200, description: "Group left; empty body."},
			{status: 400, component: "WhatsAppBadRequest"},
			{status: 403, component: "WhatsAppForbidden"},
			{status: 404, component: "WhatsAppNotFound"},
			{status: 500, component: "WhatsAppInternalServerError"},
			{status: 503, component: "WhatsAppServiceUnavailable"},
		},
	},
}
